--- 
pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 15
port: 
max_conns: 512
chdir: /var/www/leads.primedia.com/current
rackup: /var/www/leads.primedia.com/current/config.ru
max_persistent_conns: 256
environment: production
daemonize: true
address: 0.0.0.0
require: []  
servers: 4
